<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/01 22:20:59

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=mixins',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
