<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2010/02/01 22:21:58
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinebuildfilterstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildalltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllTask.class.php',
  'sfdoctrinedatadumptask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinebuildallreloadtestalltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllReloadTestAllTask.class.php',
  'sfdoctrinebuildtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinereloaddatatask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineReloadDataTask.class.php',
  'sfdoctrinerebuilddbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineRebuildDbTask.class.php',
  'sfdoctrinebuildschematask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildmodeltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinegeneratemoduletask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrinebuildsqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinecreatemodeltables' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinebasetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuildallloadtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllLoadTask.class.php',
  'sfdoctrineconfiguredatabasetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinedataloadtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinecleanmodelfilestask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrinedropdbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinebuildallreloadtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildAllReloadTask.class.php',
  'sfdoctrinegenerateadmintask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinebuildformstask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinedqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinebuilddbtask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinemigratetask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sfdoctrineinsertsqltask' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfformfilterdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfformdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfvalidatordoctrinechoicemany' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoiceMany.class.php',
  'sfvalidatordoctrineunique' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfdoctrineuniquevalidator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/validator/sfDoctrineUniqueValidator.class.php',
  'sfvalidatordoctrinechoice' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'swift_doctrinespool' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sftesterdoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfdoctrineexception' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinepager' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinecli' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfwebdebugpaneldoctrine' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfdoctrinelogger' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/log/sfDoctrineLogger.class.php',
  'sfdoctrineformgenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinecolumn' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrinegenerator' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'sfdoctrinerecord' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrinedatabase' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfdoctrineconnectionprofiler' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrineconnectionlistener' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrinedataretriever' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDataRetriever.class.php',
  'sfwidgetformdoctrinechoicemany' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoiceMany.class.php',
  'sfwidgetformdoctrineselectmany' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineSelectMany.class.php',
  'sfwidgetformdoctrineselect' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineSelect.class.php',
  'sfwidgetformdoctrinechoice' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',
  'sfdoctrineroutecollection' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineroute' => '/usr/share/php/symfony/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',

  // project
  'baseform' => '/home/wowo/localhost/mixins/lib/form/BaseForm.class.php',

  // project_model

  // application
  'myuser' => '/home/wowo/localhost/mixins/apps/frontend/lib/myUser.class.php',

  // modules
);
