<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/02/01 22:36:02
sfConfig::add(array(
  'mod_default_enabled' => true,
  'mod_default_view_class' => 'sfPHP',
  'mod_default_is_internal' => false,
));
